name: Auto Update Config File
on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Single Private File via API
        run: |
          curl -H "Authorization: token ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o load_env.js \
               -L "${{ secrets.LOAD_ENV_URL }}"

          curl -H "Authorization: token ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o update.js \
               -L "${{ secrets.UPDATE_URL }}"

      - name: Load Geetest Environment
        run: |
          node load_env.js >> $GITHUB_ENV
          rm load_env.js
               
      - name: Update Config File
        run: |
          node update.js -o config.json
          rm update.js

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "检测到配置文件已更新，正在准备提交..."
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "chore: 自动更新极验特征码 [skip ci]"
            git push
          else
            echo "配置文件无变动，跳过提交。"
          fi
